//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuji.MoveFiles.Servicio.ServicioMueveEstudio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Bibl_F33D2")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CArchivo", Namespace="http://schemas.datacontract.org/2004/07/Bibl_F33D2")]
    [System.SerializableAttribute()]
    public partial class CArchivo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] bytArchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_SitioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchClaveSitioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchfilenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vchpathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] bytArchivo {
            get {
                return this.bytArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.bytArchivoField, value) != true)) {
                    this.bytArchivoField = value;
                    this.RaisePropertyChanged("bytArchivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_Sitio {
            get {
                return this.id_SitioField;
            }
            set {
                if ((this.id_SitioField.Equals(value) != true)) {
                    this.id_SitioField = value;
                    this.RaisePropertyChanged("id_Sitio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchClaveSitio {
            get {
                return this.vchClaveSitioField;
            }
            set {
                if ((object.ReferenceEquals(this.vchClaveSitioField, value) != true)) {
                    this.vchClaveSitioField = value;
                    this.RaisePropertyChanged("vchClaveSitio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchfilename {
            get {
                return this.vchfilenameField;
            }
            set {
                if ((object.ReferenceEquals(this.vchfilenameField, value) != true)) {
                    this.vchfilenameField = value;
                    this.RaisePropertyChanged("vchfilename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchpath {
            get {
                return this.vchpathField;
            }
            set {
                if ((object.ReferenceEquals(this.vchpathField, value) != true)) {
                    this.vchpathField = value;
                    this.RaisePropertyChanged("vchpath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioMueveEstudio.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        Fuji.MoveFiles.Servicio.ServicioMueveEstudio.CompositeType GetDataUsingDataContract(Fuji.MoveFiles.Servicio.ServicioMueveEstudio.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Fuji.MoveFiles.Servicio.ServicioMueveEstudio.CompositeType> GetDataUsingDataContractAsync(Fuji.MoveFiles.Servicio.ServicioMueveEstudio.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Carga_Archivo_F33D2", ReplyAction="http://tempuri.org/IService1/Carga_Archivo_F33D2Response")]
        string Carga_Archivo_F33D2(Fuji.MoveFiles.Servicio.ServicioMueveEstudio.CArchivo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Carga_Archivo_F33D2", ReplyAction="http://tempuri.org/IService1/Carga_Archivo_F33D2Response")]
        System.Threading.Tasks.Task<string> Carga_Archivo_F33D2Async(Fuji.MoveFiles.Servicio.ServicioMueveEstudio.CArchivo request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Fuji.MoveFiles.Servicio.ServicioMueveEstudio.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Fuji.MoveFiles.Servicio.ServicioMueveEstudio.IService1>, Fuji.MoveFiles.Servicio.ServicioMueveEstudio.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Fuji.MoveFiles.Servicio.ServicioMueveEstudio.CompositeType GetDataUsingDataContract(Fuji.MoveFiles.Servicio.ServicioMueveEstudio.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Fuji.MoveFiles.Servicio.ServicioMueveEstudio.CompositeType> GetDataUsingDataContractAsync(Fuji.MoveFiles.Servicio.ServicioMueveEstudio.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string Carga_Archivo_F33D2(Fuji.MoveFiles.Servicio.ServicioMueveEstudio.CArchivo request) {
            return base.Channel.Carga_Archivo_F33D2(request);
        }
        
        public System.Threading.Tasks.Task<string> Carga_Archivo_F33D2Async(Fuji.MoveFiles.Servicio.ServicioMueveEstudio.CArchivo request) {
            return base.Channel.Carga_Archivo_F33D2Async(request);
        }
    }
}
